[package]
# Semantic Versionning is used: https://semver.org/
version = "0.0.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Mead & Hunt Enscape Camera IO"
description="Importer/exporter to exchange Enscape camera data through animation .xml."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/ericcraft-mh/meadhunt-enscape-loader"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["kit", "enscape"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}
"omni.anim.curve" = {}
"omni.anim.curve_editor" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "meadhunt.enscape.loader"
